travis:
  secure:
    BINSTAR_TOKEN: IEWB7l3KiDeXq/f4PbsNy6VZMzBiwzN466xCGnlD0FQbE/mXOoXddWRAvQLF+RzMPupvv8E5fB18fqKSbdj9m6aaTVUrrDsetrnE6qJ69Tj096JE0ARpFo8jXnIClAfmASWSqV0bmURlJRn8kUHGlYd+KV2I2mnMMuwgk+tgQr91ImSsCWAHNXFsruAePOuPmnt/hEDN9EX0D7nD846ueyUoYNH08grRGtC8RO5QGPCKUQYHBlSPl3Qiq9g8tzrRa3T35xqJ+R/EGL5+n88Fiw773r4v+da7LLAhwHc20P7VyYOzkR0cjVerGMq/lZF59x6WWnzNQi40zz3k55QIJrzqmNEKFFQr/B6bCzhZnstjaUELNvBZAAE2pZDo1el+9Vz+DA+ILHK5wtdyol2EkL7DTWYqty0IBVc9/J+Nm4jOSSEKIdukc5E/oXPOaPbg6J2vMw9iOktKWZTATy2HyG6eRadw847ferGqBKIbnJqDYEfeDY9o7jgawJuW1lBhTnxpPE5Xkj55KJFeRRcyt7oqEHjXodo9xEAy0N83V52xPqPL+Xx5VupGYvhAMJ8XS8jvAhlU86KDZ2vzcLt9S/ATb6qUQbUAW7o2bAGij6mRLOp8iNoAI6zAXiPwHS7IfRaS3w7OFEfRb9hF1qMjjkHIR+Aa+F0QQvtb0fJcQHg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
